baseURL = "https://www.nocture.dk/"
buildDrafts = false
languageCode = "en-us"
theme = "PaperMod"
title = "Jeppe Andersen Blog"

[params]
  author = "Jeppe Andersen"
  authorimage = "/images/me.png"
  description = "Code, Platform Engineering, YAML"
  copyright = "Jeppe Andersen"
  highlightjs  = true
  highlightjsstyle = "atom-one-dark"
  disableThemeToggle = true
  defaultTheme = "black"
  env = "production"

[params.assets]
  favicon = "assets/favicon.ico"
  favicon32x32 = "assets/favicon-32x32.png"
  favicon16x16 = "assets/favicon-16x16.png"
  apple_touch_icon = "assets/apple-touch-icon-144-precomposed.png"


[params.footer]
  hideCopyright = false

[params.profileMode]
  enabled = false

[params.homeInfoParams]
  content = "Code, Platform Engineering, YAML"

[[params.socialIcons]]
  name = "linkedin"
  title = "LinkedIn"
  url = "https://linkedin.com/in/jeppelundandersen"

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 100
    url = "/posts/"

[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 200
  url = "/about/"